---
repos:
- repo: https://github.com/mrtazz/checkmake.git
  rev: 0.2.2
  hooks:
  - name: Check Makefile
    id: checkmake

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - name: Check JSON
    id: check-json

  - name: Check YAML
    id: check-yaml

  - name: Check TOML
    id: check-toml

  - name: Check EOF
    id: end-of-file-fixer

  - name: Check broken symbolic link
    id: check-symlinks

  - name: Check trailing whitespace
    id: trailing-whitespace

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.9.0.2
  hooks:
  - name: Run shellcheck
    id: shellcheck
