tap "homebrew/bundle"
tap "homebrew/core"

brew "coreutils"
brew "diffutils"
brew "findutils"
brew "moreutils"
brew "grep"
brew "tree"
brew "curl"
brew "wget"
brew "tmux"
brew "git"
brew "git-lfs"
brew "gh"
brew "fzf"
brew "emacs"
brew "neovim", args: ["HEAD"]
brew "neovim-remote"
brew "starship"
brew "pre-commit"
