# Install tpm
if-shell "! git rev-parse --resolve-git-dir ${XDG_CONFIG_HOME}/tmux/plugins/tpm/.git" {
    run-shell "git clone --depth=1 https://github.com/tmux-plugins/tpm ${XDG_CONFIG_HOME}/tmux/plugins/tpm"
}

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Install dracula theme
set -g @plugin "dracula/tmux"
set -g @dracula-plugins "time cpu-usage ram-usage"
set -g @dracula-show-left-icon session
set -g @dracula-time-colors "yellow dark_gray"
set -g @dracula-cpu-usage-colors "yellow dark_gray"
set -g @dracula-ram-usage-colors "yellow dark_gray"

# Change the prefix key to Ctrl + t
set -g prefix C-t

# Send the prefix key to inner tmux process from outer tmux process.
bind C-t send-prefix

# Switch to the next pane.
bind -n M-":"   select-pane -t :.+
# Switch to the prev pane.
bind -n M-";"   select-pane -t :.-
# Switch to the pane in the specified direction.
bind -n S-left  select-pane -L
bind -n S-down  select-pane -D
bind -n S-up    select-pane -U
bind -n S-right select-pane -R

# Toggle the pane between maximized and unmaximized.
bind -n M-Enter resize-pane -Z

# Resize the pane in the specified direction.
bind -n M-left  resize-pane -L 1
bind -n M-down  resize-pane -D 1
bind -n M-up    resize-pane -U 1
bind -n M-right resize-pane -R 1

# Split the window horizontally
bind h          split-window -vc "#{pane_current_path}"
# Split the window vertically
bind v          split-window -hc "#{pane_current_path}"

# Create new window
bind Enter      new-window
# Delete the window
bind -n M-k     confirm-before 'kill-window'

# Switch to the next window
bind -n M-n     next
# Switch to the prev window
bind -n M-p     prev

# Reload tmux.conf
bind r source-file "${XDG_CONFIG_HOME}/tmux/tmux.conf"

# Initialize tmux plugins
run "${XDG_CONFIG_HOME}/tmux/plugins/tpm/tpm"
