#!/bin/bash

# Users can load Homebrew installed in a non-standard location by defining the HOMEBREW_PREFIX environment variable.
export HOMEBREW_PREFIX="${HOMEBREW_PREFIX:-/opt/homebrew}"
export HOMEBREW="${HOMEBREW_PREFIX}/bin/brew"
if [[ -x "${HOMEBREW}" ]]; then
  eval "$(${HOMEBREW} shellenv)"

  for GNUBIN_PATH in "${HOMEBREW_PREFIX}"/opt/*/libexec/gnubin; do
    export PATH="${GNUBIN_PATH}:${PATH}"
  done
  for GNUMAN_PATH in "${HOMEBREW_PREFIX}"/opt/*/libexec/gnuman; do
    export MANPATH="${GNUMAN_PATH}:${MANPATH}"
  done
fi
