on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  setup:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: make setup
      - run: make link
